import Head from 'next/head'
import { Header } from '../components/organisms/Header'
import { Presentation } from '../components/templates/Presentation'
export default function Home() {
  return (
    <div>
      <Head>
        <title>.Folio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Presentation/>
    </div>

      
  )
}
